spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/[db_name]
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=
server.port=8080

logging.file.name=
logging.logback.rollingpolicy.max-file-size=1MB
logging.level.org.springframework.web=error
logging.level.com.makeupschool.backend=error
logging.pattern.console= %d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

security.jwt.secret-key=
security.jwt.expiration-time=